### ISSUE TITLE
Цвет текста в примерах для светлой темы

### ISSUE THREAD

**Issue by AkostDev** [dragomano/alpinejs-russian#6]
Для светлой темы в блоке с примером текст остаётся белым цветом и его не видно:
![image](https://github.com/user-attachments/assets/96c0cede-0d93-44ba-b517-7118b8d5294d)

А вот в тёмной:
![image](https://github.com/user-attachments/assets/0c214357-a034-4ba7-b1f2-72996fefd8bf)

**Comment by dragomano** [comment]
На какой странице и в каком браузере? Кэш сбрасывали?

**Comment by AkostDev** [comment]
> На какой странице и в каком браузере? Кэш сбрасывали?

На всех страницах, где есть блоки с примерами.
Браузер - сафари, яндекс, хром, firefox
